#!/bin/sh

gawk '
BEGIN {
	print "# todo\n";
}

BEGINFILE {
	print "## " FILENAME "\n";
}

/.*\/\/ *TODO: / {
	sub(".*// *TODO: ", "");
	print "[" FNR "] " $0 "\n";
}
' `find -name "*.c" -or -name "*.h"` > todo.md
