# This is a basic workflow to help you get started with Actions

name: todogen

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: todogen
        run: sh ./scripts/todogen
        
      - name: commit
        run: |
          git config user.name  "todogen"
          git config user.email "invalid"
          git add todo.md
          git commit -m "todogen"
          git push origin master
